services:
  bind9-slave:
    image: ubuntu/bind9:latest
    container_name: bind9_slave
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - BIND9_USER=bind
    volumes:
      - ./config-slave:/etc/bind
      - ./cache-slave:/var/cache/bind
    restart: unless-stopped