version: '3'

services:
  ftp-server:
    image: fauria/vsftpd
    container_name: mon-serveur-ftp
    restart: always
    ports:
      - "20:20"       # Port de données FTP
      - "21:21"       # Port de commande FTP
      - "21100-21110:21100-21110" # Ports pour le mode passif
    environment:
      - FTP_USER=admin     # Ton nom d'utilisateur
      - FTP_PASS=progtr00  # Ton mot de passe
      - PASV_ADDRESS=192.168.10.253  # Remplace par l'IP de ton PC/Serveur si accès externe
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    volumes:
      - ./data:/home/vsftpd/admin # Dossier local où les configs seront sauvegardées