version: '3.8'
services:
  db-master:
    image: mariadb:latest
    container_name: mariadb_prod_master
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=progtr00
      - MARIADB_DATABASE=db-prod
      - MARIADB_USER=admin_user
      - MARIADB_PASSWORD=progtr01
    ports:
      # Format : "PORT_HOTE:PORT_CONTENEUR"
      - "3306:3306"
    volumes:
      - ./data_master:/var/lib/mysql
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row