services:
  db:
    image: mariadb:latest
    container_name: mariadb_prod
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=progtr00
      - MARIADB_DATABASE=db-prod
      - MARIADB_USER=admin_user
      - MARIADB_PASSWORD=progtr01
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - bdd-network

networks:
  bdd-network:
    driver: bridge